version: '3'
services:
  prereqs:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/prereqs/Dockerfile
    image: grpcweb/prereqs
  node-server:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/node_server/Dockerfile
    depends_on:
      - prereqs
    image: grpcweb/node-server
    ports:
      - "9090:9090"
  envoy:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
    links:
      - node-server
